Add initial multicolor support for 3 color displays
lmarzen/esp32-weather-epd pull request #32
Opened 2023-04-16 00:30 UTC by SaberShip

I've done a quick implementation of "Accent Color" support for the 3 color e-paper displays. 

Simply added a configuration for defining the accent color if DISP_3C is defined.
Updated display_utils to support setting color or using a default if not supplied. 
I've modified the following elements to use the defined accent color:
- The City/State
- Currently Active Weather Warnings
- Temperature Y-axis labels 
- Temperature Line Graph (Not the precip. chance bars)
- BME Warning in status bar (if present)
- WiFi signal status (if below configured threshold) 
- Battery status (if below configured threshold)
- All fullscreen error icons

In the future it could be relatively simple to add more configurable color thresholds for current conditions (like UV, AQI, Visibility, etc...)

Below is an image of a 3 color display running under normal conditions:
![IMG_20230415_191125](https://user-images.githubusercontent.com/6741766/232259818-c3f71022-53ff-4292-9817-81208d273679.jpg)

2023-04-18 03:26 UTC, lmarzen commented
@SaberShip I'll take a closer look this weekend if I have time and get back to you.

2023-04-21 02:33 UTC, lmarzen requested changes
Overall these additions look great, I just had two minor comments that must be addressed before merging.

2023-04-21 02:33 UTC, lmarzen commented on platformio/src/renderer.cpp
> +  if (batPercent < calcBatPercent(BATTERY_WARN_VOLTAGE)) {
Simplify this to 
`if (batVoltage < BATTERY_WARN_VOLTAGE) {`

2023-04-21 02:33 UTC, lmarzen commented on platformio/src/renderer.cpp
> +  dataColor = getWiFiColor(rssi, GxEPD_BLACK, ACCENT_COLOR);
Can we simplify this to something like this...
`dataColor = rssi >= -70 ? GxEPD_BLACK : ACCENT_COLOR'`

2023-04-21 03:52 UTC, SaberShip commented
Of course!
Done.

2023-04-21 17:24 UTC, lmarzen approved these changes
Approved.

2023-04-21 17:25 UTC, merged

2023-04-21 17:27 UTC, lmarzen commented
Thank you for your contribution @SaberShip.